### ISSUE TITLE
White spaces when part of a word has a different style

### ISSUE THREAD

**Issue by endareBrock** [oziresrds/html-to-rtf#1]
Hi,

When converting to rtf i get white spaces mid word when having 2 markups in the same word.
For example: "Re**quest**s" would become converted Re **quest** s.

I went looking in the source code and found this:
![image](https://user-images.githubusercontent.com/25737301/30542532-0814e49e-9c80-11e7-8246-abaa83d214f8.png)

removing the spaces would break the markup.

Is there a possibility to detect wether or not the markup is inside a word or not?

**Comment by oziresrds** [comment]
I'm sorry but i only looked your comment this week.
I will look this issue, thanks to report.

**Comment by oziresrds** [comment]
Hey man, you can't copy the output of terminal.
Solution, save the output at a file <fileName>.rtf
