### ISSUE TITLE
Header tags unable to convert

### ISSUE THREAD

**Issue by limcheepei** [oziresrds/html-to-rtf#11]
Taking your example, the rtf output is unable to convert header tags (e.g. h1, h2).
Pls refer to the attached zip file that contains the rtf file.

[8e72325e-7684-4265-bff6-6c0a9415ba87.zip](https://github.com/oziresrds/html-to-rtf/files/3817451/8e72325e-7684-4265-bff6-6c0a9415ba87.zip)

HTML input

`  html:string = `
  <h1>Header</h1>
  <div>
    <p style="color:#333; margin:5px;" class="test" align="center">
        text of paragraph <b>text with bold <i>text with italic and bold</i></b><i>text with italic</i>
    </p>
    <p style="color:rgb(255,0,0);" align="right">red paragraph => right with tag</p>
    <p style="color:rgb(0,0,255); text-align:center; font-size:30px;">blue paragraph => center with style</p>
      <ul>
        <li>Item 1</li>
        <li>Item 2</li>
        <li>Item 3</li>
        <li>Item 4</li>
      </ul>
    <table style="border: solid rgb(0,0,255)">
        <tbody>
            <tr>
                <td><mark>column 1</mark></td>
                <td>column 2</td>
                <td><mark>column 3</mark></td>
                <td>column 4</td>
            </tr>
            <tr>
                <td>content 1</td>
                <td>content 2<br></td>
                <td>content 3<br></td>
                <td>content 4<br></td>
            </tr>
        </tbody>
    </table>
</div> `;
`

**Comment by oziresrds** [comment]
We have already a fix in version 1.3.3.
