### ISSUE TITLE
<ul> and <ol> tags are not working

### ISSUE THREAD

**Issue by ramonribeiro96** [oziresrds/html-to-rtf#13]
I'm trying to convert this:

`let text = Converter.convertHtmlToRtf('<p>TESTE2</p><ul><li>&nbsp; TESTE</li></ul><ol><li>&nbsp; outro</li></ol>')`

but, my return is this: 

`{\rtf1\ansi\deff0{\fonttbl {\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}{\colortbl ;}{\pard TESTE2 \sb70\par}{{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\'B7}}\fi-360\li720\sa200\sl276\slmult1\lang22\f0\fs22{\pntext\tab} TESTE \par}{{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}\fi-360\li720\sa200\sl276\slmult1{\pntext\tab} outro \par}}`

**Comment by oziresrds** [comment]
What's the problem? This .rtf generate this output: 
TESTE2 
     TESTE 
     outro
