### ISSUE TITLE
TypeError: htmltoRtf.convertHtmlToRtf is not a function

### ISSUE THREAD

**Issue by hanife-create** [oziresrds/html-to-rtf#19]
Hi, 

Dear Sir,

Recently for last two weeks, I worked with your html-to-rft and heron-htmto-rtf applications. First I started using html-to-rtf, but later to use a recent one I installed "heron-html-to-rtf" module.

First of all, I want to thank for those, as they did a big favor to me in my html contents to be converted to rtf.

But in"heron-html-to-rtf" index.js the below line of codes 
**_const htmlToRtf = require('./app/src/rtf/rtf.class');
exports.htmlToRtf = new htmlToRtf();_**

throws error when trying to use htmlToRtf as function (), when I changed it to module.exports as below it works properly.

const htmlToRtf = require('./app/src/rtf/rtf.class');
//exports.htmlToRtf = new htmlToRtf();
module.exports = new htmlToRtf();

Later when I check with your gitsite, this was a fixed bug in html-to-rtf, so probably it was dismissed in "heron-hml-to-rtf" somehow.

**Comment by oziresrds** [comment]
Hi, Hanife-create.

This problem doesn't occur in the new versions.

Thanks for the information.
