### ISSUE TITLE
One question about space

### ISSUE THREAD

**Issue by zkxil** [oziresrds/html-to-rtf#22]
There are some &nbsp; in my paragraph, but after convert to rtf, I found the &nbsp; were removed.
Can you have a look at this issue?

**Comment by oziresrds** [comment]
Hi, could you put an html example here?

**Comment by zkxil** [comment]
I can't input nbsp; in this editor, there should be a & before nbsp;

![图片](https://user-images.githubusercontent.com/6679746/178660929-968648e1-0caa-477e-9336-e7af73fe9f30.png)

**Comment by zkxil** [comment]
<h1>#nbsp;#nbsp;#nbsp;Title <span style="color:rgb(255,0,0);">with</span> tag h1<h1>
can you replace the "#" with "&", after converting, you will find the the space(nbsp) is missing.

**Comment by zkxil** [comment]
any update about this issue?

**Comment by oziresrds** [comment]
Not yet.
This issue still in a queue waiting for implementation.

**Comment by oziresrds** [comment]
Please, update the package to v2.0.3 to fix that problem.
