### ISSUE TITLE
Unicode not properly output

### ISSUE THREAD

**Issue by PaoloBolzoniBusiness** [oziresrds/html-to-rtf#3]
```
var htmlToRtf = require('html-to-rtf');
var html = '<div><p>àćä</p><p>belovèd protégé, rôle coördinator, soufflés, crêpes, pâtés, ...</p></div>'
htmlToRtf.saveRtfInFile('out.rtf', htmlToRtf.convertHtmlToRtf(html))
```

Open the file in Word and you see:
**Ã Ä‡Ã¤** 
**belovÃ¨d protÃ©gÃ©, rÃ´le coÃ¶rdinator, soufflÃ©s, crÃªpes, pÃ¢tÃ©s, ...**  

Characters outside the ASCII7 have to be encoded differently, an hackish solution is:
```
var htmlToRtf = require('html-to-rtf');
var html = '<div><p>àćä</p><p>belovèd protégé, rôle coördinator, soufflés, crêpes, pâtés, ...</p></div>'
function rftcharcode(c) {
var cc = c.charCodeAt();
    return cc <= 32767 ? cc : cc -65535;
}
var rtf = htmlToRtf.convertHtmlToRtf(html);

rtf = rtf.replace(/[^\x00-\x7F]/g, function(c) { return '\\u' + rftcharcode(c) + '?'; });

htmlToRtf.saveRtfInFile('out.rtf', rtf);
```

So the file correctly displays as:
**àćä** 
**belovèd protégé, rôle coördinator, soufflés, crêpes, pâtés, ...**

However, the library should encode non-ascii7 characters properly.

**Comment by oziresrds** [comment]
Thanks for your pull request but it was not pass in all tests. 

If you do not send another pull request, when i have time i'll fix thats bugs.

PS: Before send pull request execute $ gulp tests.
Thanks.
