### ISSUE TITLE
Control characters not properly output

### ISSUE THREAD

**Issue by PaoloBolzoniBusiness** [oziresrds/html-to-rtf#4]
In the RTF file characters like { } and \\ have special meaning. They cannot appear explicitly in the text .

Try this code:
```
var htmlToRtf = require('html-to-rtf');
var html = `
<div>
  <p style="text-align:center;">I need a bit of brackets: } }</p>
  <p style="color:rgb(255,0,0);" align="right">red paragraph => right with tag</p>
</div>`;

htmlToRtf.saveRtfInFile('out.rtf', htmlToRtf.convertHtmlToRtf(html))
```

Open the resulting file, neither the curly brackets or the red paragraph will appear. In fact the output RTF will be:
```
{\rtf1\ansi\deff0{\fonttbl {\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}{\colortbl ;\red255\green0\blue0;}{\pard{\pard\qc I need a bit of brackets: } } \sb70\par}{\pard\cf1\qr red paragraph => right with tag \sb70\par}\sb70\par}}
```
The output " **I need a bit of brackets: } }** " should be " **I need a bit of brackets: \\'7D \\'7D** "
where 7D is the hex value of the } character in ASCII.

As matter of fact, the characters { } and \  has to be encoded as \\'7B \\'7D and \\'5C  respectively (otherwise one can use \\{  \\} and \\\\ respectively).

It is difficult to work around of this bug as from the output string it is difficult to distinguish between control characters and characters that are meant to go in the output text.

**Comment by oziresrds** [comment]
Thanks for your pull request but it was not pass in all tests. 

If you do not send another pull request, when i have time i'll fix thats bugs.

PS: Before send pull request execute $ gulp tests.
Thanks.
