### ISSUE TITLE
Error when converting HTML to RTF

### ISSUE THREAD

**Issue by jvarlu123456** [oziresrds/html-to-rtf#7]
Could you help me with the following error when using the library?
I'm trying to convert the html format to rtf and it seems to be malforming the rtf document.
This is the html code that happened to you
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {
margin-left: 71.25pt;
margin-right: 71.25pt;
margin-top: 71.25pt;
margin-bottom: 71.25pt;
font-size: 12pt;
text-indent: 0pt;
}
</style>
</head>
<body>
<p style=\"font-size: 18pt;\">CENTRO MÉ?DICO</p>
<p style=\"font-size: 13.5pt;\">DR. Andres</p>
<p>L a J 17:00-19:30 15 min.</p>
<p>Precio: 00 €?</p>
<p>Privado</p>
</body>
</html>
RTF obtained:
{\rtf1\ansi\deff0{\fonttbl {\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}{\colortbl ;}undefined{\pardundefined CENTRO MÉ?DICO \sb70\par}{\pardundefined DR. Andres \sb70\par}{\pard L a J 17:00-19:30 15 min. \sb70\par}{\pard Precio: 00 €? \sb70\par}{\pard Privado \sb70\par}}

**Comment by rodrigopasc** [comment]
Any update on this?

**Comment by oziresrds** [comment]
Sorry but i don't understand well what's the problem, if it persist, please open a new issue.
